name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.2
      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.30.0
      - run: go get github.com/terraform-docs/terraform-docs@v0.14.1
      - uses: pre-commit/action@v2.0.3
