repos:
  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform fmt
        entry: terraform fmt -check -recursive
        language: system
        pass_filenames: false
      - id: terraform-validate
        name: terraform validate
        entry: bash -c 'terraform init -backend=false >/dev/null && terraform validate'
        language: system
        pass_filenames: false
      - id: tflint
        name: tflint
        entry: tflint --recursive
        language: system
        pass_filenames: false
      - id: terraform-docs
        name: terraform-docs
        entry: terraform-docs .
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
